### ISSUE TITLE
Just a quick thing: I feel like moving on... (this can affect me, so closed.)

### ISSUE THREAD

**Issue by AbylTheVintageBoy** [idiotkid69/Vyond-Legacy-ACS#5]
Hey everyone... I know it's been a while but I feel a bit sad about me being gone... I want to be back.. but I don't really know... When I noticed owen publishing a new commit, it reminded me of those old days when we had lots of fun and now I feel like I wanna cry, and possibly quit because of my mom not letting me on Discord anymore.

This is no joke, I am being serious.

(also i'm sorry if this could get closed because idk how to put labels)

**Comment by OwenTheGoAnimator** [comment]
oh...

**Comment by idiotkid69** [comment]
Hey Abyl, I agree with you 100%. You can always feel free to come help us with this project. Also I will invite you to the repository, so check your email (whatever email your github account runs on) to join.
